mysql:
  host: localhost
  port: 3306
  username: root
  password: 'root'
  database: root
  ssl: false

redis:
  host: localhost
  port: 6379
  username: 'default'
  password: 'root'
  channel: chronosync

server:
group-log-id: